// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqLkVbmcNXPcLomWmeWefzcdriFyxPSS0',
    appId: '1:286378197612:web:8373fdb93fca1bae3d8e49',
    messagingSenderId: '286378197612',
    projectId: 'itds283-section1-group17-4c16c',
    authDomain: 'itds283-section1-group17-4c16c.firebaseapp.com',
    databaseURL: 'https://itds283-section1-group17-4c16c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itds283-section1-group17-4c16c.firebasestorage.app',
    measurementId: 'G-79GMF2Z8KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAICHTjQXjIcQvghQdpUhs8XjDFWU2Xmfo',
    appId: '1:286378197612:android:50515a37f44f85a03d8e49',
    messagingSenderId: '286378197612',
    projectId: 'itds283-section1-group17-4c16c',
    databaseURL: 'https://itds283-section1-group17-4c16c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itds283-section1-group17-4c16c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwd-z1NKr_h1JhvG2rt741C5TAyhPyJ2k',
    appId: '1:286378197612:ios:bb3237d2a0ef29c13d8e49',
    messagingSenderId: '286378197612',
    projectId: 'itds283-section1-group17-4c16c',
    databaseURL: 'https://itds283-section1-group17-4c16c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itds283-section1-group17-4c16c.firebasestorage.app',
    iosBundleId: 'com.example.projectphrase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwd-z1NKr_h1JhvG2rt741C5TAyhPyJ2k',
    appId: '1:286378197612:ios:bb3237d2a0ef29c13d8e49',
    messagingSenderId: '286378197612',
    projectId: 'itds283-section1-group17-4c16c',
    databaseURL: 'https://itds283-section1-group17-4c16c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itds283-section1-group17-4c16c.firebasestorage.app',
    iosBundleId: 'com.example.projectphrase2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqLkVbmcNXPcLomWmeWefzcdriFyxPSS0',
    appId: '1:286378197612:web:5dd7caca7ead638b3d8e49',
    messagingSenderId: '286378197612',
    projectId: 'itds283-section1-group17-4c16c',
    authDomain: 'itds283-section1-group17-4c16c.firebaseapp.com',
    databaseURL: 'https://itds283-section1-group17-4c16c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itds283-section1-group17-4c16c.firebasestorage.app',
    measurementId: 'G-T62JEC6VJH',
  );
}
